spring.application.name=Week3Day5

spring.datasource.url=ENC(k0kG38nMAYf5Y+BKJvKRhyjgbpsmQOu5DPriePsJlmYwQjlDXME6GaqNTBHgdVp1HvvvcX0wm7j8di0CCA9Je06JDiCih0TxK3uM+/nQW6cGPJAisbM4XvEwDo3rfKCQ)
spring.datasource.username=ENC(XpDkXuZ3eZhz7qkhOQC2NzH4IoX756AQlXOmzR5EEVkUnPTo6HmqSWIfywWgOTOO)
spring.datasource.password=ENC(roFA2+eOm5U+IVCbprwGU03JK0DngmlElZvu0bHD+Jyy+Vs+N6d+Wcrt6ar3fXQN)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD:}
